name: Update Topic On TMC Forum

on:
  push:
    branches: [ main ]

jobs:
  update-discourse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: gamemann/discourse-topic-update-action@v1.0.0
      with:
        discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
        discourse_api_user: ${{ secrets.DISCOURSE_API_USER }}
        discourse_topic_id: 0
        discourse_api_url: ${{ secrets.DISCOURSE_API_URL }}